name: Promote release bundle to TEST and STAGE

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be promoted
        required: true
        type: string

jobs:
  promote-to-test-and-stage:
    name: Promote to TEST and to STAGE
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Check if snapshot build
        run: |
          VERSION="${{ inputs.version }}"
          if [[ "$VERSION" == *"-SNAPSHOT"* ]]; then
            echo "Error: Version $VERSION is a SNAPSHOT build. Snapshots are not promoted to TEST/STAGE."
            exit 1
          fi

      - name: Setup JFrog CLI
        uses: step-security/setup-jfrog-cli@f67dd6dcfe5fab8d1ebd695c456631275009a39d # v5.2.0
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
          JF_PROJECT: ${{ vars.JFROG_PROJECT }}
        with:
          oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
          oidc-audience: ${{ vars.OIDC_AUDIENCE }}

      - name: Promoting release bundle to TEST
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@b4b1e9dc89314a2d542f9d6fe0ee150ad06f9860 # v5.0.0
        with:
          bundle-name: aerospike-jdbc
          version: ${{ inputs.version }}
          environment: TEST
          jf-project: ${{ vars.JFROG_PROJECT }}

      - name: Promoting release bundle to STAGE
        uses: aerospike/shared-workflows/.github/actions/promote-release-bundle@b4b1e9dc89314a2d542f9d6fe0ee150ad06f9860 # v5.0.0
        with:
          bundle-name: aerospike-jdbc
          version: ${{ inputs.version }}
          environment: STAGE
          jf-project: ${{ vars.JFROG_PROJECT }}
