name: Snyk scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - stage

permissions:
  contents: read
  security-events: write

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          snyk-version: v1.1297.3
          args: --all-projects --sarif-file-output=snyk.sarif

      - name: Check output file
        id: out-file
        run: |
          if test -f "snyk.sarif"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Handle undefined security-severity
        if: steps.out-file.outputs.exists == 'true'
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif

      - name: Upload result to GitHub Code Scanning
        if: steps.out-file.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # v4.38.3
        with:
          sarif_file: snyk.sarif